apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: smailandstuff
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "7e179a22-3e7d-481f-95e9-80b9e4fc04e4"
      secrets:
        - CLIENTSECRET