name: Scan git commits for secrets

on: [push]

jobs:
  scan:
    name: Scan with gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: gitleaks scan
        uses: larskaare/gitleaks-action@master