name: Scan git commits for secrets

on: [push]

jobs:
  gitleaks:
    name: Scan with gitleaks
    runs-on: ubuntu-latest
    steps:
    - uses: eshork/gitleaks-action@master
    - name: Gitleaks scan