name: Scan git commits for secrets

on: [push]

jobs:
  gitleaks:
    name: Scan with gitleaks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: docker pull zricethezav/gitleaks

      - uses: fmigneault/gitleaks-action@master
